---
version: "3.1"
services:
  nginx:
    image: nginx
    container_name: ander_nginx
    environment:
      - VIRTUAL_HOST=anderanalysis.grabski.ca
      - VIRTUAL_PORT: 80
    volumes:
      - ./src:/usr/share/nginx/html
    networks:
      - 'net'
    restart: unless-stopped

networks:
  net:
    external: true